import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Created by boro on 25.04.15.
 */
public class Starter {
    @Autowired
    private Connection connection;

    public  void createTables() throws SQLException, ClassNotFoundException, IllegalAccessException, InstantiationException {
        Statement statement = connection.createStatement();
        String sql = "CREATE TABLE USERS ("
                + "id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),"
                + "firstname VARCHAR(255) not NULL,"
                + "lastname VARCHAR(255) NOT NULL ,"
                + "age INTEGER,"
                + "PRIMARY KEY(id))";
        try {
            statement.execute(sql);
        }
        catch (SQLException e){
            if (!e.getSQLState().equals("X0Y32")) {
                throw e;
            }
        }
        sql = "CREATE TABLE ORDERS ("
                + "id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),"
                + "sellerId INTEGER not NULL,"
                + "customerId INTEGER not NULL,"
                + "totalAmount INTEGER,"
                + "PRIMARY KEY(id))";
        try {
            statement.execute(sql);
        }
        catch (SQLException e){
            if (!e.getSQLState().equals("X0Y32")) {
                throw e;
            }
        }
        connection.close();
    }

    public static void main(String args[]) throws ClassNotFoundException, SQLException, InstantiationException, IllegalAccessException {
        ApplicationContext context = new ClassPathXmlApplicationContext("mvc-dispatcher-servlet.xml");
        Starter starter = (Starter) context.getBean("starter");
        starter.createTables();

    }

}
